#ifndef __ENUM_LIBRARY_H__
#define __ENUM_LIBRARY_H__

enum SystemLed_t
{
    SYSTEM_LED_IN_RACE = 69,
    SYSTEM_LED_WAITING_RACE_START = 79,
    SYSTEM_LED_GPS = 89,
    SYSTEM_LED_STATUS = 99
};

enum LoRaMessage_t
{
    LORA_CMD_OVERTAKING_REQUEST = 0x10,
    LORA_RSP_OVERTAKING_REQUEST = 0x11,
    LORA_CMD_CONFIRM_OVERTAKING_REQUEST = 0x12,
    LORA_RSP_CONFIRM_OVERTAKING_REQUEST = 0x13,
    LORA_CMD_OVERTAKING_ACCEPT = 0x14,
    LORA_RSP_OVERTAKING_ACCEPT = 0x15
};


enum EngineState_t
{
    ENGINE_STATE_INITIALIZING = 0x01,
    ENGINE_STATE_IDLE,
    ENGINE_STATE_WAITING_RACE_START, 
    ENGINE_STATE_IN_RACE,
    ENGINE_STATE_OVERTAKING_REQUEST_RECEIVED,
    ENGINE_STATE_OVERTAKING_REQUEST_SENT,
    ENGINE_STATE_OVERTAKING_REQUEST_CONFIRMATION_RECEIVED,
    ENGINE_STATE_OVERTAKING_REQUEST_CONFIRMATION_SENT,
    ENGINE_STATE_OVERTAKING_ACCEPT_SENT,
    ENGINE_STATE_OVERTAKING_ACCEPT_RECEIVED,
    ENGINE_STATE_SOS,
    ENGINE_STATE_EMERGENCY,
    ENGINE_STATE_RACE_FINISH,
    ENGINE_STATE_CONFIGURATION
};

enum ButtonOperation_t
{
    OP_001 = 0x01,
    OP_002 = 0x02,
    OP_003 = 0x03,
    OP_004 = 0x04,
    OP_005 = 0x05    
};

enum TrackpointType_e
{
    /**
     * Trackpoint de corrida.
     */
    TRACKPOINT_TYPE_NORMAL = 0x01,
    /**
     * Trackpoint de zona de radar.
     */
    TRACKPOINT_TYPE_RADAR_ZONE = 0x02,
    /**
     * Trackpoint de deslocamento.
     */
    TRACKPOINT_TYPE_DISPLACEMENT = 0x03,
    /**
     * Trackpoint nao reconhecido.
     */
    TRACKPOINT_TYPE_ERROR = 0x99
};

enum TrackpointLocationResult_e
{
    TRACKPOINT_LOCATION_RESULT_MOVING_FORWARD = 0,
    TRACKPOINT_LOCATION_RESULT_DIDNT_CHANGE,
    TRACKPOINT_LOCATION_RESULT_OUT_OF_TRACK,
    TRACKPOINT_LOCATION_RESULT_WRONG_WAY,
    TRACKPOINT_LOCATION_RESULT_FILE_ERROR,
    TRACKPOINT_LOCATION_RESULT_WAITING_RACE_START,
    TRACKPOINT_LOCATION_RESULT_RADAR_ZONE,
    TRACKPOINT_LOCATION_RESULT_DISPLACEMENT_ZONE
};

enum SpeedAlertLevel_e
{
    SPEED_ALERT_LEVEL_20_PERC,
    SPEED_ALERT_LEVEL_20_TO_50_PERC,
    SPEED_ALERT_LEVEL_50_PERC
};

#endif // __ENUM_LIBRARY_H__